name: Daily CVE Intelligence Report

on:
  # Schedule to run every day at 00:00 UTC
  schedule:
    - cron: '0 0 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  hunt-for-cves:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files.
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas requests

    - name: Run Data Collector Script
      id: data_collection
      env:
        GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
      run: python data_collector.py

    - name: Commit and push changes
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add exploits/github/cves_github.csv
        # Check if there are changes to commit
        if git diff --staged --quiet; then
          echo "No changes to commit."
        else
          git commit -m "chore(data): Daily CVE data update"
          git push
        fi

    - name: Run CVE Hunter Script
      # Only run if the data collector found new CVEs
      if: steps.data_collection.outputs.new_cves_found == 'true'
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      run: python cve_hunter.py
